import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Copy, MessageCircle } from "lucide-react";
import { getPublicArticle } from "@/modules/phase7/service";
type Props = { params: Promise<{ slug: string }> };
async function articleOrNull(slug: string) { try { return await getPublicArticle(slug); } catch { return null; } }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = await articleOrNull(slug); if (!article) return { title: "Berita tidak ditemukan", robots: { index: false } }; return { title: article.title, description: article.excerpt || article.body.slice(0, 160), alternates: { canonical: `/berita/${slug}` }, openGraph: { title: article.title, description: article.excerpt || article.body.slice(0, 160), type: "article", publishedTime: article.publishedAt?.toISOString(), images: article.coverUrl ? [article.coverUrl] : [] }, twitter: { card: "summary_large_image", title: article.title } }; }
export const revalidate = 60;
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = await articleOrNull(slug); if (!article) notFound(); const shareText = encodeURIComponent(`${article.title} — LIGA GOAL`); return <article className="mx-auto max-w-3xl px-5 py-12 lg:px-8"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">{article.category}{article.competition && ` · ${article.competition.name}`}</p><h1 className="mt-4 font-display text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl">{article.title}</h1><div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-muted"><span>{article.organization?.name}</span><span>•</span><time>{article.publishedAt?.toLocaleDateString("id-ID", { dateStyle: "long" })}</time></div>{article.excerpt && <p className="mt-8 border-l-2 border-primary pl-5 text-lg leading-8 text-muted">{article.excerpt}</p>}<div className="mt-9 whitespace-pre-wrap text-base leading-8 text-slate-200">{article.body}</div><div className="mt-10 flex gap-3 border-t pt-6"><a className="btn-primary" href={`https://wa.me/?text=${shareText}`} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a><a className="btn-secondary" href={`/berita/${slug}`}><Copy size={16} /> Salin tautan</a></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "NewsArticle", headline: article.title, datePublished: article.publishedAt?.toISOString(), publisher: { "@type": "Organization", name: article.organization?.name || "LIGA GOAL" } }).replace(/</g, "\\u003c") }} /></article>; }
