import { Prisma } from "@prisma/client";
import { NextResponse, type NextRequest } from "next/server";
import { ZodError } from "zod";
import { ApiError, getApiActor } from "@/lib/auth/api";
import { enforceMutationRateLimit } from "@/lib/security/rate-limit";
import { actionArticle, createArticle, createNotification, listAdminArticles, updateArticle } from "@/modules/phase7/service";
type Context = { params: Promise<{ resource: string; segments?: string[] }> };
function failure(error: unknown) { if (error instanceof ApiError) return NextResponse.json({ error: error.message }, { status: error.status }); if (error instanceof ZodError) return NextResponse.json({ error: "Data tidak valid.", details: error.flatten().fieldErrors }, { status: 422 }); if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return NextResponse.json({ error: "Slug atau sumber notifikasi sudah digunakan." }, { status: 409 }); console.error("phase7-admin-api-error", error); return NextResponse.json({ error: "Terjadi kesalahan internal." }, { status: 500 }); }
export async function GET(request: NextRequest, context: Context) { try { const [{ resource }, actor] = await Promise.all([context.params, getApiActor()]); const organizationId = request.nextUrl.searchParams.get("organizationId"); if (!organizationId) throw new ApiError(400, "organizationId wajib diisi."); if (resource === "articles") return NextResponse.json({ data: await listAdminArticles(actor, organizationId) }); throw new ApiError(404, "Endpoint tidak ditemukan."); } catch (error) { return failure(error); } }
export async function POST(request: NextRequest, context: Context) { try { const [{ resource, segments = [] }, actor] = await Promise.all([context.params, getApiActor()]); const [id, action] = segments; await enforceMutationRateLimit(`${actor.id}:phase7:${resource}`, 30); const body = await request.json(); if (resource === "articles" && !id) return NextResponse.json({ data: await createArticle(actor, body) }, { status: 201 }); if (resource === "articles" && id && action === "action") return NextResponse.json({ data: await actionArticle(actor, id, body) }); if (resource === "notifications") return NextResponse.json({ data: await createNotification(actor, body) }, { status: 201 }); throw new ApiError(404, "Endpoint tidak ditemukan."); } catch (error) { return failure(error); } }
export async function PUT(request: NextRequest, context: Context) { try { const [{ resource, segments = [] }, actor] = await Promise.all([context.params, getApiActor()]); if (resource !== "articles" || !segments[0]) throw new ApiError(404, "Endpoint tidak ditemukan."); await enforceMutationRateLimit(`${actor.id}:phase7:articles:update`, 30); return NextResponse.json({ data: await updateArticle(actor, segments[0], await request.json()) }); } catch (error) { return failure(error); } }
