import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextResponse, type NextRequest } from "next/server";
import { publicCompetitionWhere } from "@/modules/phase7/service";
import { db } from "@/lib/db";

type Context = { params: Promise<{ report: string }> };
const allowed = new Set(["schedule", "results", "standings", "clubs", "players", "top-scorer", "top-assist", "bracket", "summary"]);
async function reportData(report: string, competitionId: string) {
  const competition = await db.competition.findFirst({ where: { id: competitionId, ...publicCompetitionWhere }, include: { organization: { select: { name: true } }, seasons: { orderBy: { startsAt: "desc" }, take: 1 } } });
  if (!competition) return null;
  const headings: string[] = []; const rows: Array<Array<string | number>> = [];
  if (report === "schedule" || report === "results" || report === "summary") { headings.push("Tanggal", "Tuan rumah", "Tamu", "Skor", "Status", "Venue"); const matches = await db.match.findMany({ where: { competitionId, publishedAt: { not: null }, ...(report === "results" ? { status: "OFFICIAL" as const } : {}) }, include: { homeTeam: { include: { club: true } }, awayTeam: { include: { club: true } }, venue: true }, orderBy: { kickoffAt: "asc" } }); for (const match of matches) rows.push([match.kickoffAt?.toLocaleString("id-ID", { timeZone: "Asia/Jakarta" }) || "–", match.homeTeam.club.name, match.awayTeam.club.name, match.status === "OFFICIAL" ? `${match.homeScore}-${match.awayScore}` : "–", match.status, match.venue?.name || "–"]); }
  else if (report === "standings" || report === "clubs") { headings.push("Pos", "Klub", "Main", "Menang", "Seri", "Kalah", "SG", "Poin"); const snapshot = await db.statisticsSnapshot.findFirst({ where: { competitionId, status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, include: { standings: { orderBy: { position: "asc" }, include: { club: true } } } }); for (const row of snapshot?.standings || []) rows.push([row.position, row.club.name, row.played, row.won, row.drawn, row.lost, row.goalDifference, row.points]); }
  else if (report === "players" || report === "top-scorer" || report === "top-assist") { headings.push("Pemain", "Klub", "Main", "Gol", "Assist", "Kuning", "Merah"); const snapshot = await db.statisticsSnapshot.findFirst({ where: { competitionId, status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, include: { playerStatistics: { include: { player: { select: { displayName: true, fullName: true, dateOfBirth: true, documents: { where: { type: "PARENTAL_CONSENT", isCurrent: true, verificationStatus: "APPROVED" }, select: { id: true }, take: 1 } } }, club: true }, orderBy: report === "top-assist" ? { assists: "desc" } : { goals: "desc" } } } }); const cutoff = new Date(); cutoff.setFullYear(cutoff.getFullYear() - 18); for (const row of snapshot?.playerStatistics || []) if (!row.player.dateOfBirth || row.player.dateOfBirth <= cutoff || row.player.documents.length) rows.push([row.player.displayName || row.player.fullName, row.club.name, row.appearances, row.goals, row.assists, row.yellowCards, row.redCards]); }
  else if (report === "bracket") { headings.push("Round", "Tie", "Status", "Aggregate", "Pemenang"); const ties = await db.bracketTie.findMany({ where: { competitionId }, include: { winnerTeam: { include: { club: true } } }, orderBy: [{ round: "asc" }, { position: "asc" }] }); for (const tie of ties) rows.push([tie.round, tie.label, tie.status, `${tie.aggregateHome ?? "–"}-${tie.aggregateAway ?? "–"}`, tie.status === "COMPLETED" ? tie.winnerTeam?.club.name || "–" : "Menunggu hasil resmi"]); }
  return { competition, headings, rows };
}
export async function GET(request: NextRequest, context: Context) { const { report } = await context.params; const competitionId = request.nextUrl.searchParams.get("competitionId") || ""; const format = request.nextUrl.searchParams.get("format") || "xlsx"; if (!allowed.has(report) || !competitionId || !["xlsx", "pdf"].includes(format)) return NextResponse.json({ error: "Parameter laporan tidak valid." }, { status: 400 }); const data = await reportData(report, competitionId); if (!data) return NextResponse.json({ error: "Kompetisi tidak ditemukan." }, { status: 404 }); const created = new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date()); const safeName = data.competition.slug.replace(/[^a-z0-9-]/g, ""); if (format === "xlsx") { const workbook = new ExcelJS.Workbook(); workbook.creator = "LIGA GOAL"; const sheet = workbook.addWorksheet("Laporan"); sheet.addRow(["LIGA GOAL — Semua Liga, Satu Platform"]); sheet.addRow([data.competition.name]); sheet.addRow([`Musim: ${data.competition.seasons[0]?.name || "–"}`]); sheet.addRow([`Dibuat: ${created} · Data publik resmi`]); sheet.addRow([]); const header = sheet.addRow(data.headings); header.font = { bold: true, color: { argb: "FFFFFFFF" } }; header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF101D2B" } }; data.rows.forEach((row) => sheet.addRow(row)); sheet.columns.forEach((column) => { column.width = 20; }); const buffer = await workbook.xlsx.writeBuffer(); return new NextResponse(Buffer.from(buffer), { headers: { "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": `attachment; filename="${safeName}-${report}.xlsx"`, "cache-control": "private, no-store" } }); }
  const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold); let page = pdf.addPage([842, 595]); let y = 550; const draw = (text: string, x: number, size = 8, weight = font) => page.drawText(text.slice(0, 115), { x, y, size, font: weight, color: rgb(.08, .12, .18) }); draw("LIGA GOAL", 36, 18, bold); y -= 24; draw(`${data.competition.name} · ${data.competition.seasons[0]?.name || "–"}`, 36, 12, bold); y -= 18; draw(`Dibuat ${created} · Status data: publik resmi`, 36); y -= 24; draw(data.headings.join(" | "), 36, 8, bold); y -= 14; for (const row of data.rows) { if (y < 35) { page = pdf.addPage([842, 595]); y = 550; } draw(row.join(" | "), 36); y -= 13; } const bytes = await pdf.save(); return new NextResponse(Buffer.from(bytes), { headers: { "content-type": "application/pdf", "content-disposition": `attachment; filename="${safeName}-${report}.pdf"`, "cache-control": "private, no-store" } }); }
