"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, FileCheck2, LoaderCircle, Upload, UserRound } from "lucide-react";
import { useOrganization } from "./organization-context";

type Kind = "players" | "registrations";
type Item = Record<string, unknown> & { id: string };
function object(value: unknown) { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function list(value: unknown) { return Array.isArray(value) ? value as Record<string, unknown>[] : []; }
function label(value: unknown) { return String(value || "—").replaceAll("_", " ").toLowerCase(); }

export function Phase2Detail({ kind, id }: { kind: Kind; id: string }) {
  const { organizationId } = useOrganization(); const [item, setItem] = useState<Item>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [toast, setToast] = useState("");
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(""); try { const response = await fetch(`/api/admin/phase2/${kind}/${id}?organizationId=${organizationId}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItem(result.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Data gagal dimuat."); } finally { setLoading(false); } }, [id, kind, organizationId]); useEffect(() => { const timeout = window.setTimeout(load, 0); return () => window.clearTimeout(timeout); }, [load]);
  async function workflow(action: string) { const reason = action === "reject" ? window.prompt("Alasan penolakan:") : null; if (action === "reject" && !reason) return; if (!window.confirm(`Jalankan aksi ${action} pada registrasi ini?`)) return; setBusy(true); const response = await fetch(`/api/admin/phase2/registrations/${id}/${action}?organizationId=${organizationId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); const result = await response.json(); setToast(response.ok ? `Registrasi berhasil: ${action}.` : result.error); if (response.ok) await load(); setBusy(false); }
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); form.set("playerId", kind === "players" ? id : String(object(item?.player).id)); if (kind === "registrations") form.set("registrationId", id); const response = await fetch(`/api/admin/phase2/documents?organizationId=${organizationId}`, { method: "POST", body: form }); const result = await response.json(); setToast(response.ok ? "Dokumen berhasil diunggah." : result.error); if (response.ok) { event.currentTarget.reset(); await load(); } setBusy(false); }
  async function verify(documentId: string, status: "APPROVED" | "REJECTED") { const notes = status === "REJECTED" ? window.prompt("Catatan penolakan:") : null; if (status === "REJECTED" && !notes) return; const response = await fetch(`/api/admin/phase2/documents/${documentId}/verify?organizationId=${organizationId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, notes }) }); const result = await response.json(); setToast(response.ok ? "Status dokumen diperbarui." : result.error); if (response.ok) await load(); }
  if (loading) return <main className="grid min-h-80 place-items-center"><LoaderCircle className="animate-spin text-primary"/></main>; if (error || !item) return <main className="p-6"><div className="rounded-xl border border-red-400/20 p-5 text-red-300">{error || "Data tidak ditemukan."}</div></main>;
  const player = kind === "players" ? item : object(item.player); const caps = object(item._capabilities) as Record<string, boolean>; const documents = list(item.documents); const registrations = kind === "players" ? list(item.registrations) : []; const history = kind === "registrations" ? list(item.history) : [];
  return <main className="p-4 sm:p-6 lg:p-8"><Link href={kind === "players" ? "/admin/players" : "/admin/registrations"} className="inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-white"><ArrowLeft size={16}/>Kembali</Link>
    <section className="mt-5 rounded-2xl border bg-surface/45 p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-4">{player.photoUrl ? <Image src={String(player.photoUrl)} alt="" width={72} height={72} className="size-18 rounded-2xl object-cover"/> : <span className="grid size-18 place-items-center rounded-2xl bg-white/5"><UserRound size={30}/></span>}<div><p className="text-xs font-bold uppercase tracking-widest text-primary">{kind === "players" ? "Profil pemain" : "Registrasi pemain"}</p><h1 className="mt-1 font-display text-2xl font-bold">{String(player.fullName)}</h1><p className="mt-1 text-sm capitalize text-muted">{label(player.primaryPosition)} · {label(item.status || player.status)}</p></div></div>{kind === "registrations" && <div className="flex flex-wrap gap-2">{item.status === "DRAFT" && caps["registration.submit"] && <Action onClick={() => workflow("submit")} label="Submit"/>}{["SUBMITTED","UNDER_REVIEW"].includes(String(item.status)) && caps["registration.verify"] && <Action onClick={() => workflow("verify")} label="Verifikasi"/>}{["SUBMITTED","UNDER_REVIEW"].includes(String(item.status)) && caps["registration.approve"] && <Action onClick={() => workflow("approve")} label="Approve"/>}{["SUBMITTED","UNDER_REVIEW"].includes(String(item.status)) && caps["registration.reject"] && <Action onClick={() => workflow("reject")} label="Tolak" danger/>}</div>}</div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{kind === "players" ? <><Info title="Tanggal lahir" value={player.dateOfBirth ? new Date(String(player.dateOfBirth)).toLocaleDateString("id-ID") : "—"}/><Info title="Kewarganegaraan" value={player.nationality}/><Info title="Kaki dominan" value={player.preferredFoot}/><Info title="Klub aktif" value={object(player.activeClub).name}/></> : <><Info title="Kompetisi" value={object(item.competition).name}/><Info title="Musim" value={object(item.season).name}/><Info title="Klub" value={object(item.club).name}/><Info title="Eligibility" value={item.eligibilityStatus}/></>}</div>
    </section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-surface/45 p-5"><h2 className="font-display text-lg font-bold">Dokumen privat</h2>{caps["player_document.upload"] && <form onSubmit={upload} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select name="type" required className="h-11 rounded-xl border bg-background px-3"><option value="IDENTITY">Identitas</option><option value="AGE_PROOF">Bukti usia</option><option value="PARENTAL_CONSENT">Izin orang tua</option><option value="PHOTO">Foto</option><option value="ADDITIONAL">Tambahan</option></select><input name="file" type="file" required accept="application/pdf,image/jpeg,image/png,image/webp" className="h-11 rounded-xl border px-3 py-2 text-sm"/><button disabled={busy} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 font-bold text-background"><Upload size={16}/>Unggah</button></form>}<div className="mt-4 space-y-3">{documents.length ? documents.map((document) => <div key={String(document.id)} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><a target="_blank" rel="noreferrer" href={`/api/admin/phase2/documents/${document.id}/download?organizationId=${organizationId}`} className="font-bold text-primary">{String(document.originalName)}</a><p className="mt-1 text-xs capitalize text-muted">{label(document.type)} · v{String(document.version)} · {label(document.verificationStatus)}</p></div>{caps["player_document.verify"] && document.verificationStatus === "PENDING" && <div className="flex gap-2"><button onClick={() => verify(String(document.id), "APPROVED")} className="text-sm font-bold text-emerald-300">Setujui</button><button onClick={() => verify(String(document.id), "REJECTED")} className="text-sm font-bold text-red-300">Tolak</button></div>}</div>) : <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted">Belum ada dokumen yang dapat ditampilkan.</p>}</div></section>
      <section className="rounded-2xl border bg-surface/45 p-5"><h2 className="font-display text-lg font-bold">{kind === "players" ? "Riwayat registrasi" : "Riwayat workflow"}</h2><div className="mt-4 space-y-3">{(kind === "players" ? registrations : history).length ? (kind === "players" ? registrations : history).map((record) => <div key={String(record.id)} className="rounded-xl border p-4"><div className="flex items-center gap-2"><FileCheck2 size={16} className="text-primary"/><p className="font-bold capitalize">{kind === "players" ? `${String(object(record.club).name)} · ${String(object(record.season).name)}` : `${label(record.action)} · ${label(record.toStatus)}`}</p></div><p className="mt-1 text-xs text-muted">{new Date(String(record.registrationDate || record.createdAt)).toLocaleString("id-ID")}{record.reason ? ` · ${String(record.reason)}` : ""}</p></div>) : <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted">Belum ada riwayat.</p>}</div></section></div>{toast && <div role="status" className="fixed bottom-5 right-5 rounded-xl border bg-surface px-5 py-4 text-sm shadow-2xl">{toast}</div>}
  </main>;
}
function Info({ title, value }: { title: string; value: unknown }) { return <div className="rounded-xl border p-4"><p className="text-xs font-bold uppercase tracking-wider text-muted">{title}</p><p className="mt-2 capitalize">{label(value)}</p></div>; }
function Action({ label: text, onClick, danger }: { label: string; onClick: () => void; danger?: boolean }) { return <button onClick={onClick} className={`h-10 rounded-xl border px-4 text-sm font-bold ${danger ? "text-red-300" : "text-primary"}`}>{text}</button>; }
