"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Download, LoaderCircle, Plus, Search, UserRound, X } from "lucide-react";
import { useOrganization } from "./organization-context";

type Kind = "players" | "registrations" | "squads";
type Item = Record<string, unknown> & { id: string };
type Lookup = { players: { id: string; fullName: string }[]; clubs: { id: string; name: string }[]; competitions: { id: string; name: string }[]; seasons: { id: string; name: string; competitionId: string }[]; registrations: { id: string; player: { fullName: string }; jerseyNumber: number | null }[] };
const emptyLookup: Lookup = { players: [], clubs: [], competitions: [], seasons: [], registrations: [] };
const labels = { players: ["Database pemain", "Pemain"], registrations: ["Registrasi pemain", "Registrasi"], squads: ["Manajemen skuad", "Entri skuad"] } as const;
const statuses: Record<Kind, string[]> = { players: ["ACTIVE", "INACTIVE", "RETIRED", "ARCHIVED"], registrations: ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "SUSPENDED", "CANCELLED"], squads: ["ACTIVE", "INACTIVE"] };
function object(value: unknown) { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function statusLabel(value: unknown) { return String(value || "—").replaceAll("_", " ").toLowerCase(); }

export function Phase2Manager({ kind }: { kind: Kind }) {
  const { organizationId, loading: organizationLoading } = useOrganization(); const [items, setItems] = useState<Item[]>([]); const [lookup, setLookup] = useState<Lookup>(emptyLookup); const [meta, setMeta] = useState({ page: 1, totalPages: 1, total: 0 }); const [capabilities, setCapabilities] = useState<Record<string, boolean>>({});
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(false); const [saving, setSaving] = useState(false); const [toast, setToast] = useState("");
  const load = useCallback(async () => { if (!organizationId) { setLoading(false); setItems([]); return; } setLoading(true); setError(""); try { const params = new URLSearchParams({ organizationId, page: String(page), pageSize: "10", search }); if (status) params.set("status", status); const response = await fetch(`/api/admin/phase2/${kind}?${params}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result.data); setMeta(result.meta); setCapabilities(result.capabilities || {}); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gagal memuat data."); } finally { setLoading(false); } }, [kind, organizationId, page, search, status]);
  useEffect(() => { const timeout = window.setTimeout(load, 250); return () => window.clearTimeout(timeout); }, [load]);
  useEffect(() => { if (!organizationId) return; fetch(`/api/admin/phase2/lookups?organizationId=${organizationId}`).then((response) => response.json()).then((result) => { if (result.data) setLookup(result.data); }).catch(() => undefined); }, [organizationId]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); let payload: Record<string, unknown>;
    if (kind === "players") payload = { fullName: form.get("fullName"), displayName: form.get("displayName"), dateOfBirth: form.get("dateOfBirth") || null, nationality: form.get("nationality"), primaryPosition: form.get("primaryPosition"), gender: form.get("gender"), preferredFoot: form.get("preferredFoot") || null, secondaryPositions: String(form.get("secondaryPositions") || "").split(",").map((value) => value.trim()).filter(Boolean), status: "ACTIVE" };
    else if (kind === "registrations") payload = { playerId: form.get("playerId"), competitionId: form.get("competitionId"), seasonId: form.get("seasonId"), clubId: form.get("clubId"), jerseyNumber: form.get("jerseyNumber") ? Number(form.get("jerseyNumber")) : null, idempotencyKey: crypto.randomUUID() };
    else payload = { registrationId: form.get("registrationId"), jerseyNumber: form.get("jerseyNumber") ? Number(form.get("jerseyNumber")) : null, position: form.get("position") };
    try { const response = await fetch(`/api/admin/phase2/${kind}?organizationId=${organizationId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setModal(false); setToast(`${labels[kind][1]} berhasil ditambahkan.`); await load(); } catch (cause) { setToast(cause instanceof Error ? cause.message : "Data gagal disimpan."); } finally { setSaving(false); window.setTimeout(() => setToast(""), 4500); } }
  async function release(id: string) { if (!window.confirm("Keluarkan pemain dari skuad aktif? Histori akan tetap tersimpan.")) return; const response = await fetch(`/api/admin/phase2/squads/${id}?organizationId=${organizationId}`, { method: "DELETE" }); const result = await response.json(); setToast(response.ok ? "Pemain dikeluarkan dari skuad." : result.error); if (response.ok) await load(); }
  const canCreate = kind === "players" ? capabilities.create : kind === "registrations" ? capabilities["registration.create"] : capabilities.manage;
  return <section className="rounded-2xl border bg-surface/45 p-4 sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h2 className="font-display text-xl font-bold">{labels[kind][0]}</h2><p className="mt-1 text-sm text-muted">{kind === "players" ? "Profil permanen pemain dengan data publik dan privat terpisah." : kind === "registrations" ? "Kelola pendaftaran, verifikasi, approval, dan eligibility per musim." : "Roster klub per musim, hanya untuk registrasi yang eligible."}</p></div><div className="flex flex-wrap gap-2">{kind === "squads" && organizationId && <><a className="inline-flex h-11 items-center gap-2 rounded-xl border px-4 text-sm font-bold" href={`/api/admin/phase2/squads/export?organizationId=${organizationId}&format=pdf`}><Download size={16}/>PDF</a><a className="inline-flex h-11 items-center gap-2 rounded-xl border px-4 text-sm font-bold" href={`/api/admin/phase2/squads/export?organizationId=${organizationId}&format=xlsx`}><Download size={16}/>Excel</a></>}{canCreate && <button onClick={() => setModal(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-background"><Plus size={17}/>Tambah {labels[kind][1]}</button>}</div></div>
    <div className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="flex h-11 flex-1 items-center gap-3 rounded-xl border bg-background/35 px-4"><Search size={17} className="text-muted"/><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Cari nama pemain…" className="w-full bg-transparent text-sm outline-none"/></label><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="h-11 rounded-xl border bg-background px-4 text-sm"><option value="">Semua status</option>{statuses[kind].map((value) => <option key={value}>{value}</option>)}</select></div>
    {error ? <div className="mt-6 rounded-xl border border-red-400/20 bg-red-400/5 p-5 text-sm text-red-300">{error}<button onClick={load} className="ml-3 font-bold underline">Coba lagi</button></div> : loading || organizationLoading ? <div className="mt-6 space-y-3">{[1,2,3].map((value) => <div key={value} className="h-16 animate-pulse rounded-xl bg-white/5"/>)}</div> : !items.length ? <div className="mt-6 rounded-xl border border-dashed p-10 text-center text-sm text-muted">{organizationId ? "Belum ada data." : "Pilih organisasi aktif terlebih dahulu."}</div> : <div className="mt-6 overflow-x-auto"><table className="w-full min-w-190 text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wider text-muted"><th className="px-3 py-3">Pemain</th><th className="px-3 py-3">Konteks</th><th className="px-3 py-3">Nomor / posisi</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Aksi</th></tr></thead><tbody>{items.map((item) => { const player = kind === "players" ? item : kind === "registrations" ? object(item.player) : object(object(item.registration).player); const club = kind === "players" ? object(item.activeClub) : kind === "registrations" ? object(item.club) : object(item.club); const registration = kind === "squads" ? object(item.registration) : item; return <tr key={item.id} className="border-b border-white/5"><td className="px-3 py-4"><div className="flex items-center gap-3">{player.photoUrl ? <Image src={String(player.photoUrl)} width={38} height={38} alt="" className="size-10 rounded-full object-cover"/> : <span className="grid size-10 place-items-center rounded-full bg-white/5"><UserRound size={18}/></span>}<span className="font-bold">{String(player.fullName || "—")}</span></div></td><td className="px-3 py-4"><p>{String(club.name || "—")}</p><p className="text-xs text-muted">{kind === "registrations" ? String(object(item.season).name || "") : kind === "squads" ? String(object(item.season).name || "") : `${Number(object(item._count).registrations || 0)} registrasi`}</p></td><td className="px-3 py-4">{kind === "players" ? String(item.primaryPosition || "—") : `${String(item.jerseyNumber ?? registration.jerseyNumber ?? "—")} / ${String(item.position || player.primaryPosition || "—")}`}</td><td className="px-3 py-4"><span className="rounded-full border px-2.5 py-1 text-xs capitalize">{statusLabel(kind === "squads" ? registration.eligibilityStatus : item.status)}</span></td><td className="px-3 py-4 text-right">{kind === "players" ? <Link className="font-bold text-primary" href={`/admin/players/${item.id}`}>Detail</Link> : kind === "registrations" ? <Link className="font-bold text-primary" href={`/admin/registrations/${item.id}`}>Workflow</Link> : capabilities.manage && item.status === "ACTIVE" ? <button onClick={() => release(item.id)} className="font-bold text-red-300">Keluarkan</button> : "—"}</td></tr>; })}</tbody></table></div>}
    <div className="mt-5 flex items-center justify-between text-sm text-muted"><span>{meta.total} data</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="grid size-9 place-items-center rounded-lg border disabled:opacity-30"><ChevronLeft size={16}/></button><span>{meta.page} / {meta.totalPages}</span><button disabled={page >= meta.totalPages} onClick={() => setPage((value) => value + 1)} className="grid size-9 place-items-center rounded-lg border disabled:opacity-30"><ChevronRight size={16}/></button></div></div>
    {modal && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border bg-surface p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold">Tambah {labels[kind][1]}</h3><button onClick={() => setModal(false)} aria-label="Tutup"><X/></button></div><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2">{kind === "players" ? <><Field name="fullName" label="Nama lengkap" required/><Field name="displayName" label="Nama tampilan"/><Field name="dateOfBirth" label="Tanggal lahir" type="date"/><Field name="nationality" label="Kewarganegaraan"/><Field name="primaryPosition" label="Posisi utama"/><Field name="secondaryPositions" label="Posisi sekunder (pisahkan koma)"/><Select name="gender" label="Gender" options={["UNDISCLOSED","MALE","FEMALE","OTHER"]}/><Select name="preferredFoot" label="Kaki dominan" options={["","RIGHT","LEFT","BOTH"]}/></> : kind === "registrations" ? <><SelectOptions name="playerId" label="Pemain" options={lookup.players.map((item) => [item.id,item.fullName])}/><SelectOptions name="competitionId" label="Kompetisi" options={lookup.competitions.map((item) => [item.id,item.name])}/><SelectOptions name="seasonId" label="Musim" options={lookup.seasons.map((item) => [item.id,item.name])}/><SelectOptions name="clubId" label="Klub" options={lookup.clubs.map((item) => [item.id,item.name])}/><Field name="jerseyNumber" label="Nomor punggung" type="number"/></> : <><SelectOptions name="registrationId" label="Registrasi approved" options={lookup.registrations.map((item) => [item.id, `${item.player.fullName}${item.jerseyNumber == null ? "" : ` (#${item.jerseyNumber})`}`])}/><Field name="jerseyNumber" label="Nomor punggung" type="number"/><Field name="position" label="Posisi"/></>}<div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={() => setModal(false)} className="h-11 rounded-xl border px-5 font-bold">Batal</button><button disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-background">{saving && <LoaderCircle className="animate-spin" size={16}/>}Simpan</button></div></form></div></div>}
    {toast && <div role="status" className="fixed bottom-5 right-5 z-[60] max-w-sm rounded-xl border bg-surface px-5 py-4 text-sm shadow-2xl">{toast}</div>}
  </section>;
}

function Field({ name, label, type = "text", required }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="text-sm font-semibold">{label}<input name={name} type={type} required={required} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 font-normal outline-none focus:border-primary"/></label>; }
function Select({ name, label, options }: { name: string; label: string; options: string[] }) { return <label className="text-sm font-semibold">{label}<select name={name} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 font-normal">{options.map((value) => <option key={value} value={value}>{value || "—"}</option>)}</select></label>; }
function SelectOptions({ name, label, options }: { name: string; label: string; options: [string,string][] }) { return <label className="text-sm font-semibold">{label}<select name={name} required className="mt-2 h-11 w-full rounded-xl border bg-background px-3 font-normal"><option value="">Pilih…</option>{options.map(([value,text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
