import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ClubMark, EmptyState } from "@/components/public/portal";
import { getPublicClub } from "@/modules/phase7/service";
type Props = { params: Promise<{ slug: string }> };
async function clubOrNull(slug: string) { try { return await getPublicClub(slug); } catch { return null; } }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const club = await clubOrNull(slug); if (!club) return { title: "Klub tidak ditemukan", robots: { index: false } }; return { title: club.name, description: club.description || `Profil dan statistik ${club.name}.`, alternates: { canonical: `/klub/${slug}` } }; }
export const revalidate = 120;
export default async function ClubPage({ params }: Props) { const { slug } = await params; const club = await clubOrNull(slug); if (!club) notFound(); return <><section className="border-b bg-navy/60"><div className="mx-auto flex max-w-5xl gap-6 px-5 py-12 lg:px-8"><ClubMark name={club.name} logoUrl={club.logoUrl} size="lg" /><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Profil klub</p><h1 className="mt-2 font-display text-4xl font-extrabold">{club.name}</h1><p className="mt-3 text-sm text-muted">{club.city || "Domisili belum tersedia"}{club.foundedYear && ` · Berdiri ${club.foundedYear}`}{club.homeVenue && ` · ${club.homeVenue.name}`}</p></div></div></section><section className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div className="rounded-2xl border bg-surface/60 p-6"><h2 className="font-display text-xl font-extrabold">Tentang</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-muted">{club.description || "Deskripsi klub belum tersedia."}</p><h3 className="mt-7 text-sm font-bold">Kompetisi</h3><div className="mt-3 space-y-2">{club.competitionEntries.map((entry, index) => <Link key={`${entry.competition.slug}-${index}`} href={`/kompetisi/${entry.competition.slug}`} className="block rounded-lg bg-white/[.03] p-3 text-sm hover:text-primary">{entry.competition.name} · {entry.season.name}</Link>)}</div></div><div><h2 className="font-display text-xl font-extrabold">Pemain terbaik</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{club.playerStatisticsRows.map((row) => <Link href={`/pemain/${row.player.id}`} key={`${row.player.id}-${row.appearances}`} className="flex items-center gap-3 rounded-xl border bg-surface/60 p-4"><ClubMark name={row.player.displayName || row.player.fullName} logoUrl={row.player.photoUrl} size="sm" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{row.player.displayName || row.player.fullName}</p><p className="text-xs text-muted">{row.appearances} laga · {row.assists} assist</p></div><b className="text-primary">{row.goals} gol</b></Link>)}{!club.playerStatisticsRows.length && <div className="sm:col-span-2"><EmptyState title="Belum ada statistik pemain" description="Data tampil dari snapshot resmi." /></div>}</div></div></div></section></>; }
