import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ClubMark, EmptyState } from "@/components/public/portal";
import { getPublicPlayer } from "@/modules/phase7/service";
type Props = { params: Promise<{ id: string }> };
async function playerOrNull(id: string) { try { return await getPublicPlayer(id); } catch { return null; } }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { id } = await params; const player = await playerOrNull(id); if (!player) return { title: "Profil tidak tersedia", robots: { index: false } }; const name = player.displayName || player.fullName; return { title: name, description: `Statistik publik ${name} di LIGA GOAL.`, alternates: { canonical: `/pemain/${id}` }, openGraph: { title: name, description: `Profil dan statistik resmi ${name}` } }; }
export const revalidate = 120;
export default async function PlayerPage({ params }: Props) { const { id } = await params; const player = await playerOrNull(id); if (!player) notFound(); const name = player.displayName || player.fullName; return <><section className="border-b bg-navy/60"><div className="mx-auto flex max-w-5xl flex-col items-start gap-6 px-5 py-12 sm:flex-row sm:items-center lg:px-8"><ClubMark name={name} logoUrl={player.photoUrl} size="lg" /><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Profil pemain</p><h1 className="mt-2 font-display text-4xl font-extrabold">{name}</h1><p className="mt-3 text-sm text-muted">{player.primaryPosition || "Posisi belum tersedia"} · {player.activeClub?.name || "Tanpa klub"}</p></div></div></section><section className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><h2 className="font-display text-2xl font-extrabold">Statistik per musim</h2><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[700px] text-sm"><thead className="bg-white/[.03] text-muted"><tr><th className="p-4 text-left">Kompetisi</th><th>Musim</th><th>Main</th><th>Starter</th><th>Gol</th><th>Assist</th><th>Kuning</th><th>Merah</th></tr></thead><tbody>{player.statisticsRows.map((row) => <tr className="border-t text-center" key={`${row.snapshot.competition.slug}-${row.snapshot.season.name}`}><td className="p-4 text-left"><Link className="font-bold hover:text-primary" href={`/kompetisi/${row.snapshot.competition.slug}`}>{row.snapshot.competition.name}</Link></td><td>{row.snapshot.season.name}</td><td>{row.appearances}</td><td>{row.starts}</td><td>{row.goals}</td><td>{row.assists}</td><td>{row.yellowCards}</td><td>{row.redCards}</td></tr>)}</tbody></table></div>{!player.statisticsRows.length && <div className="mt-5"><EmptyState title="Belum ada statistik" description="Statistik akan muncul setelah snapshot resmi dipublikasikan." /></div>}<h2 className="mt-12 font-display text-2xl font-extrabold">Riwayat klub publik</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{player.registrations.map((registration, index) => <Link href={`/klub/${registration.club.slug}`} key={`${registration.club.slug}-${index}`} className="rounded-xl border bg-surface/60 p-4"><p className="font-bold">{registration.club.name}</p><p className="mt-1 text-xs text-muted">{registration.competition.name} · {registration.season.name} · #{registration.jerseyNumber || "–"}</p></Link>)}</div><p className="mt-10 rounded-xl border border-primary/20 bg-primary/5 p-4 text-xs leading-6 text-muted">Profil ini sengaja tidak memuat tanggal lahir, alamat, kontak, identitas, dokumen, diagnosis medis, maupun catatan internal.</p></section></>; }
